### ISSUE TITLE
Plugin does not work with grails < 2.0 because of groovy @ToString annotation

### ISSUE THREAD

**Issue by boubbin** [desirable-objects/grails-sendgrid#11]
File _grails-sendgrid\src\groovy\uk\co\desirableobjects\sendgrid\SendGridEmail.groovy_ has annotation @ToString on line **7** which comes with _groovy.transform_ package. That Annotation is only introduced in groovy 1.8.0 and grails 1.3.9 is packaged with groovy 1.7.8 so this breaks on all grails versions before 2.0 (https://objectpartners.com/2015/05/14/list-of-groovy-versions-for-each-version-of-grails/) because of groovy

**Comment by antony** [comment]
Hi There,

I don't support Grails < 2 and I don't intend to, sorry.
If you wanted to make a pull request to fix this issue though I would happily merge it and release a Grails 1.x compatible version.

Cheers,
Antony

**Comment by boubbin** [comment]
Hello,

Yes, I actually got it working today with 1.3.9 with very little modification.

Spock could be a problem in the end but you can always exclude it if you don't care about the tests.

The reason why I made the issue was that in grails plugin portal it stated that 1.3.1 or higher. 

I can make the pull request when I'm sure everything is working good. I got at-least 4 production instances with 1.3.9 so this really gets tested :)

Sent from my iPhone

**Comment by antony** [comment]
Closing due to Grails 3 support
