### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [desirable-objects/grails-sendgrid#12]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by antony** [comment]
A good plan - but I don't currently have the time to do this. Happy to accept a PR though :)

**Comment by rpalcolea** [comment]
Hi @antony,

Regarding this issue. If you approve the Grails `3.x` I'll find some time to work on this. 

Is there a reason/preference for not using the Java SDK from Sendgrid (https://github.com/sendgrid/sendgrid-java)? 

Also, I know you aren't involved anymore with Grails and the development of the plugin but would you like to keep these improvements only for Grails `3.x` or support them on `2.x` too?

**Comment by antony** [comment]
Hi @rpalcolea - I'm going to review your PR just now.

I think when I originally wrote the plugin the Java SDK wasn't available - hence I didn't use it. It makes sense to use it, however!

I think if you decide to upgrade to SendGrid v3 we can say that v3 is Grails 3.x only - it makes no sense to backport new code, when the existing solution will work well!

**Comment by antony** [comment]
Btw - I've moved the plugin under the desirable-objects organisation.

**Comment by rpalcolea** [comment]
Hi @antony 

Oh that makes sense (the Java SDK part). Well I will take a look on the client to see if it covers everything (which I'm expecting because is the official one).

Excellent, yeah I just got the emails, thank you.

Please let me know when you push it to bintray and ask for the Grails Plugins link :)

I'm glad to help

**Comment by antony** [comment]
I've requested the grails plugins link already - so hopefully Graeme will approve that soon. It's also pushed to bintray: https://bintray.com/desirable-objects/grails-plugins

**Comment by rpalcolea** [comment]
Cool :) Oh didn't know you wrote the feature-switch plugin. I used it a few years ago, very helpful on that moment :) well let's wait for Graeme. Thanks!

**Comment by antony** [comment]
I wrote a lot of plugins, about 19 in total!

**Comment by rpalcolea** [comment]
Hi @antony, I think Graeme was on vacation, probably better to re-send the link request. I did it for another plugin and just got approved

**Comment by antony** [comment]
I'll do it asap - thanks @rpalcolea

**Comment by rpalcolea** [comment]
Thanks ! Also if you can push a new release to bintray with 2.0.1 it would be great!

**Comment by antony** [comment]
Graeme said this:

Would you mind updating the information on the bintray page with https://bintray.com/desirable-objects/grails-plugins/grails-sendgrid 

It is missing the website, issue tracker, license etc. 

Is that something we can do in the plugin's bintray integration? or do I have to do it manually?

**Comment by antony** [comment]
This is done :)

**Comment by rpalcolea** [comment]
Hi @antony 

It's weird, the plugin config has all that information: https://github.com/desirable-objects/grails-sendgrid/blob/master/src/main/groovy/uk/co/desirableobjects/sendgrid/GrailsSendgridGrailsPlugin.groovy#L20

I can take a look on why this is not working programmatically.

For now, could you modify this manually? I don't have access to your bintray repo as "admin". You can click the `Edit` link (next to  the `link` one, under the package name) and it will show you the package details, you can modify the urls there. Here is an example: https://bintray.com/docs/usermanual/uploads/uploads_editingapackage.html

Thanks

Roberto

**Comment by antony** [comment]
Oh nice - I couldn't find out how to edit the info. Bintray has to have the worst user interface I've ever seen.

**Comment by rpalcolea** [comment]
I think you could also modify the license to Apache... and yes it's kinda weird the UI

**Comment by antony** [comment]
Ah licenses licenses. I'll do that.

**Comment by antony** [comment]
Done :)
